const V={"01":"桐生","02":"戸田","03":"江戸川","04":"平和島","05":"多摩川","06":"浜名湖","07":"蒲郡","08":"常滑","09":"津","10":"三国","11":"びわこ","12":"住之江","13":"尼崎","14":"鳴門","15":"丸亀","16":"児島","17":"宮島","18":"徳山","19":"下関","20":"若松","21":"芦屋","22":"福岡","23":"唐津","24":"大村"};
const $=id=>document.getElementById(id),venue=$("venue"),status=$("status"),list=$("list"),btn=$("refresh");let DATA=[],ACTIVE=[];
const pct=x=>(Number(x)*100).toFixed(1)+"%",esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function selectedRows(){return DATA.filter(r=>String(r.jcd).padStart(2,'0')===venue.value&&Number(r.minutes_to_deadline)>0).sort((a,b)=>a.minutes_to_deadline-b.minutes_to_deadline).slice(0,2)}
function render(){if(!venue.value){list.innerHTML='<div class="empty">開催場を選択してください。</div>';return}const rows=selectedRows();if(!rows.length){list.innerHTML='<div class="empty">事前データを準備しています。準備完了後にレースを表示します。</div>';return}list.innerHTML=rows.map(r=>{const state=r.ev_status||'DATA',shown=(r.ev_rows||[]).slice().sort((a,b)=>(b.ev||0)-(a.ev||0)).slice(0,10);const lines=shown.map(b=>`<div class="bet"><div class="combo">${esc(b.combination)}</div><div class="meta">予測 ${pct(b.predicted_prob)}<br>実オッズ ${b.market_odds!=null?Number(b.market_odds).toFixed(1)+'倍':'-'}</div><div class="ev">${b.ev!=null?Number(b.ev).toFixed(2):'-'}${b.qualifies?' BUY':' PASS'}</div></div>`).join('');return `<section class="card"><div class="head"><div><div class="race">${esc(r.venue)} ${r.race_no}R</div><div class="deadline">締切まで ${Math.ceil(r.minutes_to_deadline)}分</div></div><div class="badge ${state}">${state==='BUY'?'BUY':state==='PASS'?'PASS':state==='PRE'?'事前':'待ち'}</div></div><div class="evhero"><b>${state==='BUY'?'買い候補あり':state==='PASS'?'PASS':'EV判定待ち'}</b><span>${r.best_ev!=null?'最高EV '+Number(r.best_ev).toFixed(2):''}</span></div>${lines||'<div class="meta">更新すると最大10点のEV候補を表示します。</div>'}<div class="why"><b>判定理由</b>：${state==='BUY'?'EV条件を満たす候補あり':state==='PASS'?'EV条件を満たす候補なし':state==='PRE'?'事前予想・最終判定待ち':'EV判定に必要なデータ待ち'}<br>オッズ ${r.odds_captured_at?'取得済':'未取得'} / ${r.prediction_state==='FINAL'?'展示反映済':'事前予想'}</div></section>`}).join('')}
function activeVenues(){const js=Object.keys(V),old=venue.value||localStorage.getItem('boatEvVenue');venue.innerHTML='';js.forEach(j=>venue.add(new Option(V[j],j)));if(js.includes(old))venue.value=old;else venue.value=js[0];venue.disabled=false;btn.disabled=false;venue.onchange=()=>{localStorage.setItem('boatEvVenue',venue.value);render();status.textContent=selectedRows().length?'場を切り替えました':'事前データ準備中'}}
async function board(first=false){const x=await fetch('/api/board',{cache:'no-store'});if(!x.ok)throw Error('board '+x.status);const p=await x.json();DATA=p.board||[];ACTIVE=p.active_venues||[];activeVenues();render();}
async function refresh(){if(!venue.value)return;btn.disabled=true;const t=Date.now();status.textContent='更新開始';try{const x=await fetch('/api/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selected_jcds:[venue.value],source:'user'})});if(!x.ok)throw Error('更新開始失敗');for(;;){await new Promise(r=>setTimeout(r,1000));const s=await (await fetch('/api/refresh-status',{cache:'no-store'})).json();status.textContent=s.running?`展示・最新オッズ取得中 ${s.elapsed_sec||0}秒`:`更新完了 ${((Date.now()-t)/1000).toFixed(0)}秒`;if(!s.running)break}await board(false)}catch(e){status.textContent='更新失敗：'+e.message}finally{btn.disabled=!venue.value}}
btn.onclick=refresh;
(async()=>{try{await board(true);status.textContent=selectedRows().length?'準備済み':'事前データ準備中'}catch(e){status.textContent='読込失敗：'+e.message;btn.disabled=true}})();
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js?v=205').catch(()=>{});
